### ISSUE TITLE
oracle 生成实体类报错

### ISSUE THREAD

**Issue by mzbzyc** [baomidou/generator#151]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本: 3.5.1

​	数据库版本: oracle 11g

​	模板引擎版本: velocity-engine-core

#### 问题详情
        生成实体类时报错： java.lang.AbstractMethodError: oracle.jdbc.driver.T4CConnection.setSchema(Ljava/lang/String;)V
        具体报错日志：
Exception in thread "main" java.lang.AbstractMethodError: oracle.jdbc.driver.T4CConnection.setSchema(Ljava/lang/String;)V
	at com.baomidou.mybatisplus.generator.config.DataSourceConfig.getConn(DataSourceConfig.java:203)
	at com.baomidou.mybatisplus.generator.config.querys.DecoratorDbQuery.<init>(DecoratorDbQuery.java:58)
	at com.baomidou.mybatisplus.generator.IDatabaseQuery$DefaultDatabaseQuery.<init>(IDatabaseQuery.java:97)
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.getTableInfoList(ConfigBuilder.java:139)
	at com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine.batchOutput(AbstractTemplateEngine.java:226)
	at com.baomidou.mybatisplus.generator.AutoGenerator.execute(AutoGenerator.java:179)
	at com.baomidou.mybatisplus.generator.FastAutoGenerator.execute(FastAutoGenerator.java:213)

**Comment by mzbzyc** [comment]
把DataSourceConfig.java 第203行，connection.setSchema(schemaName);去掉就可以了

**Comment by codeicu** [comment]
> 

6

**Comment by qmdx** [comment]
@mzbzyc @codeicu  你们的办法都可以解决，应该是驱动和数据库版本对不上导致
