### ISSUE TITLE
可否不依赖模板引擎包正常运行 ？

### ISSUE THREAD

**Issue by hn-chenji** [baomidou/generator#197]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本:3.5.1

​	数据库版本:mysql5.7

​	模板引擎版本:默认

#### 问题详情
  可以不依赖模板引擎包吗，项目纯api输出，不想项目中加多余的依赖包
#### 错误结果
Caused by: java.lang.ClassNotFoundException: org.apache.velocity.context.Context
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)

#### 期望结果
不依赖模板引擎包，也能运行

**Comment by qmdx** [comment]
这种需求，那么请你自己实现引擎接口（自行处理），即可
