### ISSUE TITLE
不支持南大通用GBase代码生成

### ISSUE THREAD

**Issue by xiaoqhuang** [baomidou/generator#21]
### 当前使用版本(必填,否则不予处理)
v3.4.1

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
GBase版本v8.8 3.0.0
jdbc driver: com.gbasedbt.jdbc.Driver
jdbc url: jdbc:gbasedbt-sqli://ip

### 重现步骤(如果有就写完整)
配置gbase连接后运行代码生成报错，
能确认连接是成功的
说语法错误，跟踪SQL语句为"show table status where 1=1 and name in ('某个表名')"
改语句客户端执行也不支持

### 报错信息
java.sql.SQLException: A syntax error has occurred.

at com.gbasedbt.util.IfxErrMsg.getSQLException(IfxErrMsg.java:408)

at com.gbasedbt.jdbc.IfxSqli.a(IfxSqli.java:3502)

at com.gbasedbt.jdbc.IfxSqli.D(IfxSqli.java:3782)

at com.gbasedbt.jdbc.IfxSqli.dispatchMsg(IfxSqli.java:2684)

at com.gbasedbt.jdbc.IfxSqli.receiveMessage(IfxSqli.java:2609)

at com.gbasedbt.jdbc.IfxSqli.executePrepare(IfxSqli.java:1244)

at com.gbasedbt.jdbc.IfxPreparedStatement.f(IfxPreparedStatement.java:307)

at com.gbasedbt.jdbc.IfxPreparedStatement.a(IfxPreparedStatement.java:288)

at com.gbasedbt.jdbc.IfxPreparedStatement.<init>(IfxPreparedStatement.java:181)

at com.gbasedbt.jdbc.IfxSqliConnect.h(IfxSqliConnect.java:6181)

at com.gbasedbt.jdbc.IfxSqliConnect.prepareStatement(IfxSqliConnect.java:2486)

at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.getTablesInfo(ConfigBuilder.java:363)

at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.<init>(ConfigBuilder.java:113)

at com.baomidou.mybatisplus.generator.AutoGenerator.execute(AutoGenerator.java:96)

at com.xmgps.api.prototype.BaseCodeGenerator.generate(BaseCodeGenerator.java:102)

at com.xmgps.api.prototype.BaseCodeGenerator.generate(BaseCodeGenerator.java:117)

at com.xmgps.api.prototype.BaseCodeGenerator.main(BaseCodeGenerator.java:326)

Caused by: java.sql.SQLException

at com.gbasedbt.util.IfxErrMsg.getSQLException(IfxErrMsg.java:408)

at com.gbasedbt.jdbc.IfxSqli.D(IfxSqli.java:3787)

... 14 more

**Comment by 836219171** [comment]
建议修改一下标题，不支持Gbase 8s版本，Gbase 8a版本是支持的。Gbase 8s版本基于INFORMIX，Gbase 8a版本基于mysql，默认走mysql的生成方式是可以的。

**Comment by qmdx** [comment]
请 PR
