### ISSUE TITLE
3.5.1配置oscar提示找不到合适的jdbc驱动

### ISSUE THREAD

**Issue by 453629963** [baomidou/generator#216]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本: 3.5.1

​	数据库版本: 神通数据库7

​	模板引擎版本: velocity 2.3

#### 问题详情
项目使用oscarJDBC16链接神通数据库，3.4.0版本时，使用new DataSourceConfig()的方式配置数据源，代码生成器运行正常。现在升到3.5.1后，按照官网示例，配置数据源后一直提示找不到jdbc驱动，代码如下：
`
FastAutoGenerator.create(
             new DataSourceConfig.Builder(
                "jdbc:oscar://127.0.0.1:2003/osrdb?searchpath=DUTCMS", "sysdba", "123456").dbQuery(new OscarQuery()).typeConvert(new OscarTypeConvert()
        ))................
`

pom中的包
`

<dependency>
    <groupId>com.oscar</groupId>
    <artifactId>oscarJDBC16</artifactId>
    <version>16</version>
</dependency>

<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-boot-starter</artifactId>
    <version>3.4.3.3</version>
</dependency>

<dependency>
    <groupId>com.baomidou</groupId>
    <artifactId>mybatis-plus-generator</artifactId>
    <version>3.5.1</version>
</dependency>

<dependency>
    <groupId>org.apache.velocity</groupId>
    <artifactId>velocity-engine-core</artifactId>
    <version>2.3</version>
</dependency>`

#### 复现步骤

按官方文档配置好各参数，引入jdbc包，然后运行main方法。

#### 错误结果

`
Exception in thread "main" java.lang.RuntimeException: 无法创建文件，请检查配置信息！
	at com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine.batchOutput(AbstractTemplateEngine.java:244)
	at com.baomidou.mybatisplus.generator.AutoGenerator.execute(AutoGenerator.java:179)
	at com.baomidou.mybatisplus.generator.FastAutoGenerator.execute(FastAutoGenerator.java:213)
	at com.ht.generator.CodeGeneratorMain.main(CodeGeneratorMain.java:155)
Caused by: java.lang.RuntimeException: java.sql.SQLException: No suitable driver found for jdbc:oscar://127.0.0.1:2003/osrdb?searchpath=DUTCMS
	at com.baomidou.mybatisplus.generator.config.DataSourceConfig.getConn(DataSourceConfig.java:206)
	at com.baomidou.mybatisplus.generator.config.querys.DecoratorDbQuery.<init>(DecoratorDbQuery.java:58)
	at com.baomidou.mybatisplus.generator.IDatabaseQuery$DefaultDatabaseQuery.<init>(IDatabaseQuery.java:97)
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.getTableInfoList(ConfigBuilder.java:139)
	at com.baomidou.mybatisplus.generator.engine.AbstractTemplateEngine.batchOutput(AbstractTemplateEngine.java:226)
	... 3 more
Caused by: java.sql.SQLException: No suitable driver found for jdbc:oscar://127.0.0.1:2003/osrdb?searchpath=DUTCMS
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.baomidou.mybatisplus.generator.config.DataSourceConfig.getConn(DataSourceConfig.java:196)
	... 7 more

进程已结束，退出代码为 1

`

#### 期望结果

希望可以正常链接神通数据库生成代码。

**Comment by zhangxin0w0** [comment]
这个问题Oracle也有，试试手动加载驱动类，Oracle这样就不会报错了，Class.forName("oracle.jdbc.driver.OracleDriver");

**Comment by 453629963** [comment]
> 这个问题Oracle也有，试试手动加载驱动类，Oracle这样就不会报错了，Class.forName（“oracle.jdbc.driver.OracleDriver”）;

万分感谢，有用的，太谢谢了
