### ISSUE TITLE
3.5.2版本发生ClassNotFoundException

### ISSUE THREAD

**Issue by cleverMarmot** [baomidou/generator#235]
请将问题描述清楚,别耽误彼此打(xi)工(jiao)赚(nen)钱(mo)的时间.
如果能直接提供错误示例,请上传仓库或私发邮箱,对于私发邮箱的代码,承诺不泄露来源方信息(邮箱名,公司名等信息),阅后即焚.

#### 版本信息

​	生成器版本: 3.5.2

​	数据库版本:5.5.19

​	模板引擎版本: 包里是什么版本就是什么版本

#### 问题详情
  用了velocity、beetl都不行，运行main方法就报错，查了一些博客说包里用的模板语言版本太老了，要自己引入更新的版本，
  随后我引入了模板语言更新版本的依赖之后就可以了；

#### 错误结果
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/beetl/core/ResourceLoader
	at com.smartcamp.GeneratorCodeTest.main(GeneratorCodeTest.java:34)
Caused by: java.lang.ClassNotFoundException: org.beetl.core.ResourceLoader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
```

#### 期望结果
   希望版本更新的时候，把包里模板语言的依赖包版本也更新一下，就不用我们自己再去引入更新的依赖了！

**Comment by cleverMarmot** [comment]
> @cleverMarmot 哪个模板的版本出现这个问题，贴一下pom
	生成器3.5.2版本里引入的模板引擎是什么版本就是什么版本；
<dependency>
      <groupId>org.apache.velocity</groupId>
      <artifactId>velocity-engine-core</artifactId>
      <version>2.3</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.freemarker</groupId>
      <artifactId>freemarker</artifactId>
      <version>2.3.31</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>com.ibeetl</groupId>
      <artifactId>beetl</artifactId>
      <version>3.7.0.RELEASE</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
