### ISSUE TITLE
代码生成关于达梦1.6版本数据库sql语句不匹配

### ISSUE THREAD

**Issue by chen1749144759** [baomidou/generator#3]
### 当前使用版本(必填,否则不予处理)
- mybatis-plus generater 3.4.0
- DM数据库1.6

### 该问题是如何引起的？(确定最新版也有问题再提!!!)
com.baomidou.mybatisplus.generator.config.builder 包
ConfigBuilder 类
getTablesInfo 方法 
this.dataSourceConfig.getDbQuery().tablesSql(); 获取SQL语句问题
```
SELECT * FROM (SELECT DISTINCT T1.TABLE_NAME AS TABLE_NAME,T2.COMMENTS AS TABLE_COMMENT FROM USER_TAB_COLUMNS T1 INNER JOIN USER_TAB_COMMENTS T2 ON T1.TABLE_NAME = T2.TABLE_NAME) WHERE 1=1 
```
### 重现步骤(如果有就写完整)
正常配置逆向工程参数

### 报错信息
java.sql.SQLException: 无效的表或视图名 'USER_TAB_COLUMNS' 
	at dm.jdbc.dbaccess.DBError.throwSQLException(Unknown Source)
	at dm.jdbc.driver.DmdbCSI.prepareSQL(Unknown Source)
	at dm.jdbc.driver.DmdbStatement.directExec(Unknown Source)
	at dm.jdbc.driver.DmdbPreparedStatement.initialize(Unknown Source)
	at dm.jdbc.driver.DmdbPreparedStatement.<init>(Unknown Source)
	at dm.jdbc.driver.DmdbConnection.prepareStatement(Unknown Source)
	at dm.jdbc.driver.DmdbConnection.prepareStatement(Unknown Source)
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.getTablesInfo(ConfigBuilder.java:471)
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.handlerStrategy(ConfigBuilder.java:277)
	at com.baomidou.mybatisplus.generator.config.builder.ConfigBuilder.<init>(ConfigBuilder.java:137)
	at com.baomidou.mybatisplus.generator.AutoGenerator.execute(AutoGenerator.java:96)
	at net.yk.wind_p4.config.MybatisPlusGenerator.generator(MybatisPlusGenerator.java:86)
	at net.yk.wind_p4.config.MybatisPlusGenerator.main(MybatisPlusGenerator.java:62)
![微信截图_20200831130928](https://user-images.githubusercontent.com/45381400/91684854-3deac900-eb8b-11ea-8025-0c757ad578e6.png)

**Comment by qmdx** [comment]
非主流数据库只接受 PR
